### ISSUE TITLE
Issue When Exporting via Command Line

### ISSUE THREAD

**Issue by netshade** [AdrienQuillet/godot-traits#9] opened 2024-02-12 03:00 UTC
I'm experiencing an issue w/ Godot Traits present in a project when exporting a project via the CLI. I use the following command:

`/Applications/Godot.app/Contents/MacOS/Godot  --headless -v --editor --export-release "Linux/X11" "builds/linux/example.x86_64"`

and while, previously, this worked fine for creating a release build for my project, it now appears that when Godot Traits is active in the project, all of my other assets ( GDScripts, PNGs, et al ) do not get included in the result binary. This causes the final executable to crash at runtime as it cannot locate any assets.

I've included a test project here to reproduce the behavior. When exporting the final build via the CLI as in the above example, you should see the `globals.gd` file included in the output - it does not when Godot Traits is enabled, however.

I have temporarily worked around this by removing the `.godot` directory entirely before attempting a CLI export. I do not have a good explanation currently for why that works, however; my theory was that it causes Godot force a filesystem re-import before Godot Traits attempts to cause a script reload. 

[GodotTraitBugExample.zip](https://github.com/AdrienQuillet/godot-traits/files/14234947/GodotTraitBugExample.zip)

**Comment by Earewien** [comment] 2024-02-14 12:10
Hey

Thank you for reporting this bug! I managed to reproduce the issue with your example on Windows. I don't know yet the cause, but a possible workaround (solution?) is to disable addon when exporting :

In godot-traits.gd, replace all 
```gdscript
if Engine.is_editor_hint():
```

by 

```gdscript
if Engine.is_editor_hint() and not OS.get_cmdline_args().has("--export-debug") and not OS.get_cmdline_args().has("--export-release"):
```

This will avoid to launch the addon in export mode (unfortunatly, `--headless` arg is not found in `OS.get_cmdline_args()` 🐙)

I will try to find the root cause, but if I can't this workaround will be committed into next release.

**Comment by Earewien** [comment] 2024-02-14 12:47
Okayyyy

So it turns out it's caused by the `gdscript saver`script: when saving the newly generated script (at startup), all other resources are excluded from export.

When exporting the game, this `GTraits`script should be exactly the same as the committed (exporting) one. But I don't check before saving it, so it causes a re-save, and this issue.

I can not just compare file contents before saving them since they are generated multiples times with different content. 

So:
- I need to fix the multiple generation at startup
- Then, check that if `GTraits` content is the same, it's not needed to resave/reload it,
- Finally, when exporting project, if `GTraits` content has changed, it should be treated as an error, since we can not regenrate file during game export, and if content has changed, game will likely not work.

😸

**Comment by netshade** [comment] 2024-02-14 13:17
Nice find - I don't know Godot Engine / editor internals very much, but do you think it would be a fair assessment to say that this more of a Godot bug than `godot-traits` bug? Because the idea of "saving a script causes other resources to be excluded from export" seems like a fault of the underlying framework, at least at a distance.

**Comment by Earewien** [comment] 2024-02-14 20:26
Hey

Indeed this behavior is strange. I do not find an issue reporting that in Godot project (I always do borderline stuff... So I'm not surprised 🙀!)

I still need to fix things on my side, we can see it as optimizations but it's a workaround for this issue too (even if big is submitted to Godot Engine project, several weeks can pass without any fix) 

Do you want to open an issue or do you want me to do it ?


Le 14 février 2024 14:17:39 GMT+01:00, Chris Zelenak ***@***.***> a écrit :

**Comment by netshade** [comment] 2024-02-16 01:16
I "think" I might have found a fix. I suspect this is still a Godot bug, but I wanted to show you what I did and see what you thought.

In `gtraits_gdscript_saver.gd`, in `do_save_script`, it looks like:

```

 func _do_save_script(script:Script, script_path:String) -> void:
     script.resource_path = script_path
     DirAccess.make_dir_recursive_absolute(script.resource_path.get_base_dir())
     var error = ResourceSaver.save(script, script.resource_path, ResourceSaver.FLAG_CHANGE_PATH)
     if error != OK:
         _logger.warn(func(): return "⚠️ Unable to save script content into '%s': %s" % [script.resource_path, error_string(error)])
```

I changed it to:

```
func _do_save_script(script:Script, script_path:String) -> void:
     flag = ResourceSaver.NONE
     if script.resource_path != script_path:
       script.resource_path = script_path
       flag = ResourceSaver.FLAG_CHANGE_PATH
     DirAccess.make_dir_recursive_absolute(script.resource_path.get_base_dir())
     var error = ResourceSaver.save(script, script.resource_path, flag)
     if error != OK:
         _logger.warn(func(): return "⚠️ Unable to save script content into '%s': %s" % [script.resource_path, error_string(error)])
```

and then the export seems to work as I'd expect using that example project. I'm not extremely familiar with Godot however, so please forgive me if I have missed important parts of saving that script.

**Comment by Earewien** [comment] 2024-02-16 12:13
Hi

I tested your modifications, but it does not work for me (on Windows...?)

```gdscript
func _do_save_script(script:Script, script_path:String) -> void:
     var flag = ResourceSaver.FLAG_NONE
     if script.resource_path != script_path:
       script.resource_path = script_path
       flag = ResourceSaver.FLAG_CHANGE_PATH
     DirAccess.make_dir_recursive_absolute(script.resource_path.get_base_dir())
     var error = ResourceSaver.save(script, script.resource_path, flag)
     if error != OK:
         _logger.warn(func(): return "⚠️ Unable to save script content into '%s': %s" % [script.resource_path, error_string(error)])
```

Only part of resources are exported
```
[gtraits_helper_gen  ][INFO ] Generating GTraits helper due to changes
[gtraits_plugin      ][INFO ]  Godot Traits loaded !
savepack: begin: Packing steps: 102
        savepack: step 2: Storing File: res://gtraits/helper/gtraits.gd
        savepack: step 102: Storing File: res://.godot/global_script_class_cache.cfg
        savepack: step 102: Storing File: res://icon.svg
        savepack: step 102: Storing File: res://.godot/uid_cache.bin
        savepack: step 102: Storing File: res://project.binary
savepack: end
[gtraits_plugin      ][INFO ]  Godot Traits unloaded !
```

But, when doing nothing in the `_do_save_script` function, I get
```
[gtraits_helper_gen  ][INFO ] Generating GTraits helper due to changes
[gtraits_plugin      ][INFO ]  Godot Traits loaded !
savepack: begin: Packing steps: 102
        savepack: step 2: Storing File: res://addons/godot-traits/core/builder/gtraits_trait_builder.gd
        savepack: step 7: Storing File: res://addons/godot-traits/core/gdscript/gtraits_gdscript_parser.gd
        savepack: step 13: Storing File: res://addons/godot-traits/core/gdscript/gtraits_gdscript_saver.gd
        savepack: step 18: Storing File: res://addons/godot-traits/core/gdscript/gtraits_type_oracle.gd
        savepack: step 24: Storing File: res://addons/godot-traits/core/log/gtraits_logger.gd
        savepack: step 29: Storing File: res://addons/godot-traits/core/util/gtraits_hash.gd
        savepack: step 35: Storing File: res://addons/godot-traits/core/gtraits_core.gd
        savepack: step 40: Storing File: res://addons/godot-traits/core/gtraits_storage.gd
        savepack: step 46: Storing File: res://addons/godot-traits/fs/gtraits_filesystem.gd
        savepack: step 52: Storing File: res://addons/godot-traits/helper/gtraits_helper_generator.gd
        savepack: step 57: Storing File: res://addons/godot-traits/settings/gtraits_editor_settings.gd
        savepack: step 63: Storing File: res://addons/godot-traits/godot-traits.gd
        savepack: step 68: Storing File: res://gtraits/helper/gtraits.gd
        savepack: step 74: Storing File: res://attachable.gd
        savepack: step 79: Storing File: res://globals.gd
        savepack: step 85: Storing File: res://.godot/imported/icon.svg-218a8f2b3041327d8a5756f3a245f83b.ctex
        savepack: step 85: Storing File: res://icon.svg.import
        savepack: step 90: Storing File: res://.godot/exported/133200997/export-3070c538c03ee49b7677ff960a3f5195-main.scn
        savepack: step 96: Storing File: res://Node3D.gd
        savepack: step 102: Storing File: res://main.tscn.remap
        savepack: step 102: Storing File: res://.godot/global_script_class_cache.cfg
        savepack: step 102: Storing File: res://icon.svg
        savepack: step 102: Storing File: res://.godot/uid_cache.bin
        savepack: step 102: Storing File: res://project.binary
savepack: end
[gtraits_plugin      ][INFO ]  Godot Traits unloaded !
```

I will emit a workaround for this case for now :)

**Comment by Earewien** [comment] 2024-02-16 12:53
@netshade I created a pull request with a workaround
Let me known if it works for you :)

PR: https://github.com/AdrienQuillet/godot-traits/pull/10
Branch to test: https://github.com/AdrienQuillet/godot-traits/tree/issue/9-issue-when-exporting-via-command-line

**Comment by netshade** [comment] 2024-02-23 14:51
Sorry it took me a second to check this out - I tried this out on my sample project and it seemed to do the trick. Thanks for making the change :)

**Comment by Earewien** [comment] 2024-02-23 19:37
Don't worry, I wad doing a secret santa jam :) so it's a perfect timing
I will merge this fix in master, it will be in next release (tomorrow, I hope)

**Closed as completed** 2024-02-23 19:38 UTC
Labels: 🐞 Bug

**Comment by netshade** [comment] 2024-02-24 15:40
You're awesome, thx for the fix.
